export const global = [
    'b',  'c',  'd',  'f',  'g',  'h',  'j',  'k',  'l',  'm',  'n',  'p',  'q',  'r',  's',  't',  'v',  'w',  'x',  'y',  'z',  
    'bb', 'cb', 'db', 'fb', 'gb', 'hb', 'jb', 'kb', 'lb', 'mb', 'nb', 'pb', 'qb', 'rb', 'sb', 'tb', 'vb', 'wb', 'xb', 'yb', 'zb', 
    'bc', 'cc', 'dc', 'fc', 'gc', 'hc', 'jc', 'kc', 'lc', 'mc', 'nc', 'pc', 'qc', 'rc', 'sc', 'tc', 'vc', 'wc', 'xc', 'yc', 'zc', 
    'bd', 'cd', 'dd', 'fd', 'gd', 'hd', 'jd', 'kd', 'ld', 'md', 'nd', 'pd', 'qd', 'rd', 'sd', 'td', 'vd', 'wd', 'xd', 'yd', 'zd', 
    'bf', 'cf', 'df', 'ff', 'gf', 'hf', 'jf', 'kf', 'lf', 'mf', 'nf', 'pf', 'qf', 'rf', 'sf', 'tf', 'vf', 'wf', 'xf', 'yf', 'zf', 
    'bg', 'cg', 'dg', 'fg', 'gg', 'hg', 'jg', 'kg', 'lg', 'mg', 'ng', 'pg', 'qg', 'rg', 'sg', 'tg', 'vg', 'wg', 'xg', 'yg', 'zg', 
    'bh', 'ch', 'dh', 'fh', 'gh', 'hh', 'jh', 'kh', 'lh', 'mh', 'nh', 'ph', 'qh', 'rh', 'sh', 'th', 'vh', 'wh', 'xh', 'yh', 'zh', 
    'bj', 'cj', 'dj', 'fj', 'gj', 'hj', 'jj', 'kj', 'lj', 'mj', 'nj', 'pj', 'qj', 'rj', 'sj', 'tj', 'vj', 'wj', 'xj', 'yj', 'zj', 
    'bk', 'ck', 'dk', 'fk', 'gk', 'hk', 'jk', 'kk', 'lk', 'mk', 'nk', 'pk', 'qk', 'rk', 'sk', 'tk', 'vk', 'wk', 'xk', 'yk', 'zk', 
    'bl', 'cl', 'dl', 'fl', 'gl', 'hl', 'jl', 'kl', 'll', 'ml', 'nl', 'pl', 'ql', 'rl', 'sl', 'tl', 'vl', 'wl', 'xl', 'yl', 'zl', 
    'bm', 'cm', 'dm', 'fm', 'gm', 'hm', 'jm', 'km', 'lm', 'mm', 'nm', 'pm', 'qm', 'rm', 'sm', 'tm', 'vm', 'wm', 'xm', 'ym', 'zm', 
    'bn', 'cn', 'dn', 'fn', 'gn', 'hn', 'jn', 'kn', 'ln', 'mn', 'nn', 'pn', 'qn', 'rn', 'sn', 'tn', 'vn', 'wn', 'xn', 'yn', 'zn', 
    'bp', 'cp', 'dp', 'fp', 'gp', 'hp', 'jp', 'kp', 'lp', 'mp', 'np', 'pp', 'qp', 'rp', 'sp', 'tp', 'vp', 'wp', 'xp', 'yp', 'zp', 
    'bq', 'cq', 'dq', 'fq', 'gq', 'hq', 'jq', 'kq', 'lq', 'mq', 'nq', 'pq', 'qq', 'rq', 'sq', 'tq', 'vq', 'wq', 'xq', 'yq', 'zq', 
    'br', 'cr', 'dr', 'fr', 'gr', 'hr', 'jr', 'kr', 'lr', 'mr', 'nr', 'pr', 'qr', 'rr', 'sr', 'tr', 'vr', 'wr', 'xr', 'yr', 'zr', 
    'bs', 'cs', 'ds', 'fs', 'gs', 'hs', 'js', 'ks', 'ls', 'ms', 'ns', 'ps', 'qs', 'rs', 'ss', 'ts', 'vs', 'ws', 'xs', 'ys', 'zs', 
    'bt', 'ct', 'dt', 'ft', 'gt', 'ht', 'jt', 'kt', 'lt', 'mt', 'nt', 'pt', 'qt', 'rt', 'st', 'tt', 'vt', 'wt', 'xt', 'yt', 'zt', 
    'bv', 'cv', 'dv', 'fv', 'gv', 'hv', 'jv', 'kv', 'lv', 'mv', 'nv', 'pv', 'qv', 'rv', 'sv', 'tv', 'vv', 'wv', 'xv', 'yv', 'zv', 
    'bw', 'cw', 'dw', 'fw', 'gw', 'hw', 'jw', 'kw', 'lw', 'mw', 'nw', 'pw', 'qw', 'rw', 'sw', 'tw', 'vw', 'ww', 'xw', 'yw', 'zw', 
    'bx', 'cx', 'dx', 'fx', 'gx', 'hx', 'jx', 'kx', 'lx', 'mx', 'nx', 'px', 'qx', 'rx', 'sx', 'tx', 'vx', 'wx', 'xx', 'yx', 'zx', 
    'by', 'cy', 'dy', 'fy', 'gy', 'hy', 'jy', 'ky', 'ly', 'my', 'ny', 'py', 'qy', 'ry', 'sy', 'ty', 'vy', 'wy', 'xy', 'yy', 'zy', 
    'bz', 'cz', 'dz', 'fz', 'gz', 'hz', 'jz', 'kz', 'lz', 'mz', 'nz', 'pz', 'qz', 'rz', 'sz', 'tz', 'vz', 'wz', 'xz', 'yz', 'zz', 
]